dist: focal
language: node_js
# node_js:
#   - "18" # Ensure compatibility with your Node.js version

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test -- --watchAll=false --runInBand --headless # Run tests in headless mode and without watch

after_success:
  - npm run build
  - firebase deploy --token $FIREBASE_DEPLOY_TOKEN # Deploy on success
