dist: focal
language: node_js
node_js:
  - "lts/*" # Ensure compatibility with your Node.js version

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g firebase-tools

script:
  - npm run build  # Build your app

after_success:
  - firebase deploy --token $FIREBASE_DEPLOY_TOKEN  # Deploy to Firebase if build is successful

deploy:
  provider: script
  skip_cleanup: true
  script:
    - firebase deploy --token $FIREBASE_DEPLOY_TOKEN  # Ensure deployment
  on:
    branch: main  # Only deploy from the main branch (adjust if you use a different branch)
